### ISSUE TITLE
If app tab is not opened, coverage watch fails

### ISSUE THREAD

**Issue by HugoHeneault** [serut/meteor-coverage#41] opened 2016-09-30 09:23 UTC
It seems that if I only open http://app.dev:3000/coverage page, coverage fails.

## Expected Behavior

With only our coverage tab opened, we should have good coverage results.

## Current Behavior

With http://app.dev:3000/coverage and http://app.dev:3000/ tabs opened:
![capture du 2016-09-30 11-19-11](https://cloud.githubusercontent.com/assets/4112256/18987033/0021054c-8700-11e6-888b-0fd5f3f7de86.png)
![capture du 2016-09-30 11-19-31](https://cloud.githubusercontent.com/assets/4112256/18987032/001b648e-8700-11e6-99cf-85156daa8674.png)

With only http://app.dev:3000/coverage
![capture du 2016-09-30 11-20-21](https://cloud.githubusercontent.com/assets/4112256/18987038/06fdb45a-8700-11e6-8119-c150c94680b7.png)
![capture du 2016-09-30 11-20-39](https://cloud.githubusercontent.com/assets/4112256/18987039/071cb396-8700-11e6-9c8b-6cf4a6444110.png)

## Steps to Reproduce (for bugs)
1. Run `meteor test --settings settings.coverage.json --driver-package practicalmeteor:mocha`
2. Go to http://app.dev:3000/coverage
3. Coverage report is wrong

## Context
I want to have only one coverage tab opened -- not both app and coverage
Or at least, a note about it on the Readme :book:

**Comment by serut** [comment] 2016-09-30 13:45
This is not a bug : if you do not execute the javascript code by running test, the coverage is low. When you open the other tab, it runs tests and javascript is executed and marked as executed.

**Closed by serut** 2016-09-30 13:45 UTC
